SRC = my_snake_to_camel.c

all:
	@cc -g my_snake_to_camel.c -o my_snake_to_camel
	@./my_snake_to_camel "here_is_a_snake_case_word"
	@./my_snake_to_camel "hello_world" | cat -e
	@./my_snake_to_camel | cat -e
