SRC = my_inter.c

all:
	cc -g $(SRC) -o my_inter
	@./my_inter "padinton" "paqefwtdjetyiytjneytjoeyjnejeyj" | cat -e
	@./my_inter ddf6vewg64f gtwthgdwthdwfteewhrtag6h4ffdhsd | cat -e
	@./my_inter "rien" "cette phrase ne cache rien" | cat -e
	@./my_inter | cat -e
