SRC = my_inter.c

all:
	cc -Wall -Wextra -Werror -g $(SRC) -o my_inter
	@./my_inter "padinton" "paqefwtdjetyiytjneytjoeyjnejeyj" | cat -e
	@./my_inter ddf6vewg64f gtwthgdwthdwfteewhrtag6h4ffdhsd | cat -e
	@./my_inter "rien" "cette phrase ne cache rien" | cat -e
	@./my_inter "aaabbbcccdddeee" "kjn,mnjekljdlknm,nm,nm,cn,mn,nd,mn,macdab" | cat -e
	@./my_inter "nothing" | cat -e
	@./my_inter "nothing" "nothing" | cat -e
	@./my_inter "nothing" "nothing" "nothing" | cat -e
	@./my_inter "vinnicius" "not_here" | cat -e
	@./my_inter "" "" | cat -e
	@./my_inter "apple" "banana" | cat -e
	@./my_inter "banana" "a" | cat -e
	@./my_inter | cat -e
