SRC = my_pgcd.c

all:
	@cc -g -Wall -Wextra -Werror $(SRC) -o my_pgcd
	@ ./my_pgcd 42 10 | cat -e
	@ ./my_pgcd 42 12 | cat -e
	@ ./my_pgcd 14 77 | cat -e
	@ ./my_pgcd 17 3 | cat -e 
	@ ./my_pgcd | cat -e
