SRC = my_hidenp.c

all:
	@cc -g -Wall -Wextra -Werror $(SRC) -o my_hidenp
	@./my_hidenp "fgex.;" "tyf34gdgf;'ektufjhgdgex.;.;rtjynur6" | cat -e
	@./my_hidenp "abc" "2altrb53c.sse" | cat -e
	@./my_hidenp "abc" "btarc" | cat -e
	@./my_hidenp | cat -e
