SRC = my_union.c

all:
	@cc -g -Wall -Wextra -Werror $(SRC) -o my_union
	@./my_union "zpadinton" "paqefwtdjetyiytjneytjoeyjnejeyj" | cat -e
	@echo zpadintoqefwjy$
	@./my_union ddf6vewg64f gtwthgdwthdwfteewhrtag6h4ffdhsd | cat -e
	@echo df6vewg4thras$
	@./my_union "rien" "cette phrase ne cache rien" | cat -e
	@echo rienct phas$
	@./my_union | cat -e
	@echo $
	@./my_union "rien" | cat -e
	@echo $
