SRC = my_fprime.c

all:
	@cc -g -Wall -Wextra -Werror $(SRC) -o my_fprime
	@ ./my_fprime 225225 | cat -e
	@ ./my_fprime 8333325 | cat -e
	@ ./my_fprime 9539 | cat -e
	@ ./my_fprime 804577 | cat -e
	@ ./my_fprime 42 | cat -e
	@ ./my_fprime 1 | cat -e
	@ ./my_fprime | cat -e
	@ ./my_fprime 42 21 | cat -e
