
SRC = my_wdmatch.c

all:
	cc -g -Wall -Wextra -Werror $(SRC) -o wdmatch
	@./wdmatch "faya" "fgvvfdxcacpolhyghbreda" | cat -e
	@./wdmatch "faya" "fgvvfdxcacpolhyghbred" | cat -e
	@./wdmatch "quarante deux" "qfqfsudf arzgsayns tsregfdgs sjytdekuoixq " | cat -e
	@./wdmatch "error" rrerrrfiiljdfxjyuifrrvcoojh | cat -e
	@./wdmatch | cat -e
